# Generated by Django 4.1.7 on 2023-03-23 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSchedule',
            fields=[
                ('store_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dayOfWeek', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('start_time_local', models.TimeField()),
                ('end_time_local', models.TimeField()),
                ('timezone_str', models.CharField(default='America/Chicago', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_utc', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=10)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='sm_api.storeschedule')),
            ],
        ),
    ]
