# Generated by Django 4.1.7 on 2023-03-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_api', '0002_store_alter_storestatus_status_businesshours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
