# Generated by Django 4.1.7 on 2023-03-24 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_api', '0003_alter_store_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='end_time_local',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='start_time_local',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
