# Generated by Django 4.1.7 on 2023-03-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_api', '0005_rename_end_time_local_businesshours_end_time_utc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete')], default='running', max_length=10)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
    ]
