# Generated by Django 4.1.7 on 2023-04-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_api', '0007_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(default='running', max_length=10),
        ),
    ]
